"""Initial migration.

Revision ID: c84c0ed373b9
Revises: 
Create Date: 2024-10-27 13:13:27.002840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84c0ed373b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('msg_count', sa.Integer(), nullable=False),
    sa.Column('chat_ctx', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_session')
    # ### end Alembic commands ###
